module.exports = [
  {
    image: "p1.png",
    color: "gray",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "long-sleeve",
    cat3Name: "Long Sleeve",
    name: "Classic No Tuck Dress Shirt",
    price: 49.50,
    rating: 4,
    url: "products/001.html",
    id: "4001"
  },
  {
    image: "p2.png",
    color: "black",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "long-sleeve",
    cat3Name: "Long Sleeve",
    name: "Multistack Everyday Shirt",
    price: 65,
    rating: 3,
    url: "products/002.html",
    id: "4002"
  },
  {
    image: "p3.png",
    color: "violet",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "strapless",
    cat3Name: "Strapless",
    name: "A-Line Strapless Chiffon Floor-Length Dress",
    price: 109.99,
    rating: 5,
    url: "products/003.html",
    id: "4003"
  },
  {
    image: "p4.png",
    color: "red",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "sleeveless",
    cat3Name: "Sleeveless",
    name: "Sweetheart Sleeveless Short Tulle Homecoming Dress",
    price: 99,
    rating: 4,
    url: "products/004.html",
    id: "4004"
  },
  {
    image: "p5.png",
    color: "black",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "pockets",
    cat3Name: "Pockets",
    name: "Coopertown Black Velvet Pocket Dress",
    price: 26.99,
    rating: 3,
    url: "products/005.html",
    id: "4005"
  },
  {
    image: "p6.png",
    color: "multi-colored",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "collections",
    cat3Name: "Collections",
    name: "Floral Print Dress Collection",
    price: 49.99,
    rating: 2,
    url: "products/006.html",
    id: "4006"
  },
  {
    image: "p7.png",
    color: "black",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "strapless",
    cat3Name: "Strapless",
    name: "Strapless Neckline Gown",
    price: 299.99,
    rating: 5,
    url: "products/007.html",
    id: "4007"
  },
  {
    image: "p8.png",
    color: "blue",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "long-sleeve",
    cat3Name: "Long Sleeve",
    name: "Mens Elegant Turndown Collar Shirt With Chest Pocket",
    price: 22.99,
    rating: 5,
    url: "products/008.html",
    id: "4008"
  },
  {
    image: "p9.png",
    color: "blue",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "long-sleeve",
    cat3Name: "Long Sleeve",
    name: "B Fresh, The Jazzy J, With Pearl Snaps",
    price: "69.99",
    rating: 4,
    url: "products/009.html",
    id: "4009"
  },
  {
    image: "p10.png",
    color: "green",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "long-sleeve",
    cat3Name: "Long Sleeve",
    name: "B Fresh, Elegant Western Cowboy",
    price: "69.99",
    rating: 4,
    url: "products/010.html",
    id: "4010"
  },
  {
    image: "p11.png",
    color: "green",
    cat1Tag: "mens",
    cat1Name: "Men's",
    cat2Tag: "shirts",
    cat2Name: "Shirts",
    cat3Tag: "short-sleeve",
    cat3Name: "Short Sleeve",
    name: "Classic Plaid Pattern Men's Stylish Short Sleeve Button Up, Summer Holiday Shirt",
    price: "12.49",
    rating: 3,
    url: "products/011.html",
    id: "4011"
  },
  {
    image: "p12.png",
    color: "purple",
    cat1Tag: "womens",
    cat1Name: "Women's",
    cat2Tag: "dress",
    cat2Name: "Dress",
    cat3Tag: "strapless",
    cat3Name: "Strapless",
    name: "Star Print Strapless Gown For Spring & Summer",
    price: 99.79,
    rating: 5,
    url: "products/012.html",
    id: "4012"
  }
];
